# Generated by Django 5.1.3 on 2024-11-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
