# Generated by Django 5.1.3 on 2024-11-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_customer_customer_id_alter_expense_expense_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='MACN1QBY', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(default='6J9BA98K', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='SYAVX7V4', max_length=20, unique=True),
        ),
    ]
