# Generated by Django 5.1.3 on 2024-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_customer_customer_id_alter_expense_expense_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='C66KG4SP', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(default='ZZ3X7EE6', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card')], default='Cash', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Reimbursed', 'Reimbursed')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='A5OGSF53', max_length=20, unique=True),
        ),
    ]
