# Generated by Django 5.1.3 on 2024-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_customer_customer_id_alter_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='Z7XQI6SL', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(default='TDZ8S7RP', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='RBJP9T86', max_length=20, unique=True),
        ),
    ]
