# Generated by Django 5.1.3 on 2024-11-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_customer_customer_id_alter_expense_expense_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='B1EKBYR7', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(default='9G769Y3A', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='9VXMPAX1', max_length=20, unique=True),
        ),
    ]
