# Generated by Django 5.1.3 on 2024-11-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_order_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True),
        ),
    ]
