# Generated by Django 5.1.4 on 2024-12-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('started_date', models.DateField()),
                ('logo', models.ImageField(upload_to='business_logos/')),
                ('currency', models.CharField(max_length=10)),
                ('currency_symbol_placement', models.CharField(choices=[('Before', 'Before Amount'), ('After', 'After Amount')], max_length=10)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_country', models.CharField(max_length=100)),
                ('business_state', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'business setting',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/profileImage')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('Rider', 'Rider'), ('Staff', 'Staff')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_details', models.TextField()),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_details', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_agreement', models.FileField(blank=True, null=True, upload_to='documents/staff_agreements/')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='documents/verification_documents/')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.staff')),
            ],
        ),
    ]
