# Generated by Django 5.1.3 on 2024-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businesssetting_options_alter_staff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='GSZFP57E', max_length=20, unique=True),
        ),
    ]
