# Generated by Django 5.1.3 on 2024-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='OVHEA54Y', max_length=20, unique=True),
        ),
    ]
