# Generated by Django 5.1.3 on 2024-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='J0P64X4Y', max_length=20, unique=True),
        ),
    ]
