# Generated by Django 5.1.3 on 2024-11-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='9MODBZB3', max_length=20, unique=True),
        ),
    ]
