# Generated by Django 5.1.3 on 2024-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_staff_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_details',
            field=models.TextField(default='Bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='HMMBENCG', max_length=20, unique=True),
        ),
    ]
