# Generated by Django 5.1.3 on 2024-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_staff_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='25CGMYQC', max_length=20, unique=True),
        ),
    ]
