# Generated by Django 5.1.3 on 2024-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profileImage'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
