# Generated by Django 5.1.3 on 2024-11-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_staff_profile_image_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_agreement',
            field=models.FileField(blank=True, null=True, upload_to='documents/staff_agreements/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/verification_documents/'),
        ),
    ]
